artifacts_root: artifacts

data_extraction:
  source_url: "https://drive.google.com/file/d/1dLr9oiwqYrHvztjKOl92zw__yq0Pnw5K/view?usp=sharing"
  prefix: "https://drive.google.com/uc?/export=download&id="
  local_data_file: artifacts/data_ingestion/data.csv
  local_load_dir: artifacts/data_ingestion

data_schema_validation:
  gender        :          object
  age            :          int32
  hypertension    :         int64
  heart_disease    :        int64
  smoking_history   :      object
  bmi               :     float64
  HbA1c_level        :    float64
  blood_glucose_level :     int64
  diabetes             :    int64


data_transformation:
  transformation_artifact_file: artifacts/data_transformation/transform.pkl
  target_feature : "diabetes"
