artifacts_root: artifacts

data_extraction:
  source_url: "https://drive.google.com/file/d/1N-X8aij_9FtAtrDBfRHQKGE0vtIUC67i/view?usp=sharing"
  prefix: "https://drive.google.com/uc?/export=download&id="
  local_data_file: artifacts/data_ingestion/clean_data.csv
  local_load_dir: artifacts/data_ingestion